name: Security Pipeline

on:
  push:
    branches: [ main, master, develop, temp ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  security:
    uses: helgif/DevSecOps_Pipelines/.github/workflows/security-pipeline-template.yml@main
    with:
      node_version: '20'
      enable_fuzzing: true
    # secrets:
    #   SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}